"""Initial database schema

Revision ID: 936285312d73
Revises: 
Create Date: 2026-07-15 15:34:31.048232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936285312d73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('subjek', sa.String(length=150), nullable=True),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('posisi', sa.String(length=150), nullable=False),
    sa.Column('perusahaan', sa.String(length=150), nullable=False),
    sa.Column('durasi', sa.String(length=100), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=True),
    sa.Column('nama_panggilan', sa.String(length=100), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telepon', sa.String(length=50), nullable=True),
    sa.Column('universitas', sa.String(length=150), nullable=True),
    sa.Column('fakultas', sa.String(length=150), nullable=True),
    sa.Column('prodi', sa.String(length=150), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('gambar_url', sa.String(length=255), nullable=True),
    sa.Column('link_project', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama_skill', sa.String(length=100), nullable=False),
    sa.Column('icon_class', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_table('projects')
    op.drop_table('profiles')
    op.drop_table('experiences')
    op.drop_table('users')
    op.drop_table('contacts')
    # ### end Alembic commands ###
